// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDxiVJfm82s6tG3h2b3M8cUqFEpDjFfP8',
    appId: '1:259513525534:android:2db7f91f70284ddf57d50f',
    messagingSenderId: '259513525534',
    projectId: 'plantavor-2',
    databaseURL: 'https://plantavor-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plantavor-2.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVeFQQocG09ELp1DxWbhTKOCfqv8UxXJw',
    appId: '1:259513525534:web:19cd831dcf9ba87557d50f',
    messagingSenderId: '259513525534',
    projectId: 'plantavor-2',
    authDomain: 'plantavor-2.firebaseapp.com',
    databaseURL: 'https://plantavor-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plantavor-2.appspot.com',
    measurementId: 'G-BE7TCG7G5V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQktqguZHD0_bQVDKekEEO1eZcnoiP6gY',
    appId: '1:259513525534:ios:5885003b5b22d86f57d50f',
    messagingSenderId: '259513525534',
    projectId: 'plantavor-2',
    databaseURL: 'https://plantavor-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plantavor-2.appspot.com',
    iosBundleId: 'com.example.plantavor',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQktqguZHD0_bQVDKekEEO1eZcnoiP6gY',
    appId: '1:259513525534:ios:5885003b5b22d86f57d50f',
    messagingSenderId: '259513525534',
    projectId: 'plantavor-2',
    databaseURL: 'https://plantavor-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plantavor-2.appspot.com',
    iosBundleId: 'com.example.plantavor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVeFQQocG09ELp1DxWbhTKOCfqv8UxXJw',
    appId: '1:259513525534:web:bf54305b375c47ac57d50f',
    messagingSenderId: '259513525534',
    projectId: 'plantavor-2',
    authDomain: 'plantavor-2.firebaseapp.com',
    databaseURL: 'https://plantavor-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plantavor-2.appspot.com',
    measurementId: 'G-5HB44ECCQ9',
  );

}